### ISSUE TITLE
Why not use `spec = { { import = "kickstart.plugins" } }` instead of all these requires?

### ISSUE THREAD

**Issue by brxxlstxrs** [dam9000/kickstart-modular.nvim#11]
Why not use `spec = { { import = "kickstart.plugins" } }` instead of all these requires?

**Comment by dam9000** [comment]
For a couple of reasons:

1. Some of these plugins are disabled by default in the original kickstart:
```
  -- require 'kickstart.plugins.debug',
  -- require 'kickstart.plugins.indent_line',
```
By using `import = "kickstart.plugins"` these would also get enabled.

2. The plugins contain comments that are easiest to follow if you go in the same order as they are in the original kickstart, so one can move to a specific plugin hit `ctrl-]` to jump to that file and `ctrl-o` to get back

3. by explicitly listing the plugins here it's easier to disable a single one by commenting it out (`--`)

With all that said, perhaps it would be better indeed to just include all, it would simplify adding new plugins, as for disabling existing, one can still use a flag `enabled = false` or `return {}` inside the plugin file. So, I'm undecided what is the best approach. Opinions?

**Comment by brxxlstxrs** [comment]
in general I prefer the built-in pure lua `require()` over the **lazy.nvim** interface, but if we use **lazy.nvim** then why not omit one of these tables unnecessarily and use lazy.nvim as intended.

An example of how folke does this:
https://github.com/LazyVim/starter/blob/main/lua/config/lazy.lua

**Comment by dam9000** [comment]
@brxxlstxrs right, I understand how to use the `{ import = "kickstart.plugins" }` however, I'd like to keep this project functionally the same as the original kickstart where these two plugins are disabled:
```
  -- require 'kickstart.plugins.debug',
  -- require 'kickstart.plugins.indent_line',
```
If I add `{ import = "kickstart.plugins" }` then it would be a change in behaviour compared to the original kickstart, so if I want to keep the same behavior I will need to disable those two plugins in some other way, for example by adding the `enabled = false` flag inside those plugins. But then I also need to update the instructions on how to enable/disable these two plugins. So I'm not sure which way will be cleaner but also more understandable for the user. That's my dilemma.

**Comment by brxxlstxrs** [comment]
as i already said, i think `require` is ok, and leave it as it is - very good

**Comment by dam9000** [comment]
Ok, thanks for the feedback!
