### ISSUE TITLE
Mason failed to install stylua

### ISSUE THREAD

**Issue by KikeSenpai** [dam9000/kickstart-modular.nvim#12]
## Describe the bug

When I enter neovim mason fails to install stylua.

## To Reproduce

1. Open neovim in my `/.config/nvim` folder using `nvim .` You can se my config [here](https://github.com/KikeSenpai/nvim).

## Desktop

- OS: Linux (WSL), Ubuntu
- Terminal: Windows terminal

## Neovim Version

NVIM 0.9.4
Build type: Release
LuaJIT 2.1.1692716794
system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
```
```

**Comment by dam9000** [comment]
Also, I have no experience with WSL, can you provide some quick instructions how to setup that?
Not sure if I should treat this as a linux or windows issue, but it works fine for me in both environments (windows and linux).

Can you provide more details, for starters the mason.log, such as:
```
C:\Users\vbox\AppData\Local\nvim-data>cat mason.log
[INFO  2/29/2024 12:52:13 PM] ...m-data/lazy/mason.nvim/lua/mason-core/installer/init.lua:184: Executing installer for Package(name=lua-language-server) {}
[INFO  2/29/2024 12:52:13 PM] ...m-data/lazy/mason.nvim/lua/mason-core/installer/init.lua:184: Executing installer for Package(name=stylua) {}
[INFO  2/29/2024 12:52:17 PM] ...m-data/lazy/mason.nvim/lua/mason-core/installer/init.lua:245: Installation succeeded for Package(name=stylua)
[INFO  2/29/2024 12:52:19 PM] ...m-data/lazy/mason.nvim/lua/mason-core/installer/init.lua:245: Installation succeeded for Package(name=lua-language-server)
```
The Mason/stylua works fine for me:
```
 Installed
    ◍ lua-language-server lua_ls
    ◍ stylua
      An opinionated Lua code formatter.

      installed version v0.20.0                                 
      homepage          https://github.com/JohnnyMorganz/StyLua 
      languages         Lua, Luau                               
      categories        Formatter                               
      executables       stylua.cmd        
```

using these windows install instructions:
https://github.com/nvim-lua/kickstart.nvim/blob/master/README.md#windows-installation

```
install [chocolatey](https://chocolatey.org/install) either follow the instructions on the page or use winget, run in cmd as admin:
winget install --accept-source-agreements chocolatey.chocolatey
install all requirements using choco, exit previous cmd and open a new one so that choco path is set, run in cmd as admin:
choco install -y neovim git ripgrep wget fd unzip gzip mingw make
```

**Comment by dam9000** [comment]
Ok, I tried out WSL and it works fine for me, here is what I tried:
```
wsl --install
wsl
sudo add-apt-repository ppa:neovim-ppa/unstable -y
sudo apt update
sudo apt install neovim make gcc ripgrep unzip
git clone https://github.com/dam9000/kickstart-modular.nvim.git "$HOME/.config/nvim"
nvim
```
not sure how you installed nvim, but using the ppa/unstable as seen above installs the version 0.10
and from my testing it works fine.

**Comment by KikeSenpai** [comment]
I removed my configuration and re-started from scratch as you did and now it works perfectly, I forked this repo and I will re-add the modifications that I had done so far.
Thanks a lot.

**Comment by KikeSenpai** [comment]
I removed my configuration and re-started from scratch as you did and now it works perfectly, I forked this repo and I will re-add the modifications that I had done so far.
Thanks a lot.
