### ISSUE TITLE
Defined colorscheme not loaded correctly.

### ISSUE THREAD

**Issue by marnux** [dam9000/kickstart-modular.nvim#18]
## Describe the bug
When mason installs something new, the colorscheme config seems to be applied as expected. After closing and  opening nvim again, the colorscheme loaded, seems to be tokyonight instead of tokyonight-night as defined in the tokyonight.lua.

When checking :scriptnames in both cases, i see that when opening without any mason interaction the last script executed is ~/.local/share/nvim/lazy/tokyonight.nvim/colors/tokyonight.lua, while it is not when Mason is executed upon opening nvim.

## To Reproduce
1. Install the repo as nvim config
2. Start nvim, mason installs a bunch of plugins
3. The theme is tokyonight-night
4. Close nvim
5. Open nvim
6. The theme is now tokyonight

## Desktop
- OS: Debian 12
- Terminal: Gnome terminal

## Neovim Version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

I have searched all lua files, i could find and there does not seem to be any hidden call to tokyonight, which would cause the default theme to be overwritten.
Any insight would be appreciated.

**Comment by dam9000** [comment]
The plugin manager that starts automatically at first nvim startup and is visible is `Lazy` not `Mason`, but it's true `Mason` is also running in background installing the LSP plugins. Anyway, I'm not able to reproduce this issue, and I have tried it with `distrobox debian12` can you perhaps make a video or a couple of screenshots?  Anyway, perhaps this change will fix the issue:
```
diff --git a/lua/kickstart/plugins/tokyonight.lua b/lua/kickstart/plugins/tokyonight.lua
index 3e5e74d..51a77c4 100644
--- a/lua/kickstart/plugins/tokyonight.lua
+++ b/lua/kickstart/plugins/tokyonight.lua
@@ -6,6 +6,10 @@ return {
     -- If you want to see what colorschemes are already installed, you can use `:Telescope colorscheme`.
     'folke/tokyonight.nvim',
     priority = 1000, -- Make sure to load this before all the other start plugins.
+    lazy = false,
+    opts = {
+      style = 'night',
+    },
     init = function()
       -- Load the colorscheme here.
       -- Like many other themes, this one has different styles, and you could load
```
Let me know if this helps.

**Comment by marnux** [comment]
Indeed it's Lazy instead of Mason. I tried the suggestions, but to no avail.
I have backed up my config and started from scratch. Attaching a video of the process, That way you can see the strange behaviour in action.

https://github.com/dam9000/kickstart-modular.nvim/assets/33655142/929fd29d-ad39-44b6-9931-f991c7cea722

I hope it's clear enough. The cloning starts from a straight up fork of your repo, as i would like to keep the config around when i finish setting it up.

**Comment by marnux** [comment]
Adding a screenshot of the scriptnames list and as you can see the last line is a call to tokyonight. I'm not expecting that to be there.

![image](https://github.com/dam9000/kickstart-modular.nvim/assets/33655142/31d05e31-5394-4b30-bf5f-e11fcdb2c102)

**Comment by dam9000** [comment]
Hmm, that seems to be tokyonight 'day' style, perhaps it's because of this:
https://github.com/folke/tokyonight.nvim?tab=readme-ov-file#%EF%B8%8F-configuration
> The [day](https://github.com/folke/tokyonight.nvim?tab=readme-ov-file#day) style is used when { style = "day" } is passed to setup(options) **or when vim.o.background = "light".**

Did you change `vim.o.background` to `light`? Although it does not seem so from your video capture. Perhaps there's a system init that changes it? Perhaps it's tied to system theme.
Can you run:
```
:lua print(vim.o.background)
```
or:
```
:set background?
```
and check the output?

**Comment by marnux** [comment]
Ok, that explains the switch to light probably. I get light back on those commands. The problem is that it is not set in the config as far as i know and i removed all settings before using the kickstart config. Maybe your suggestion of something on the system setting it, is valid.
Overwrote it in the options to dark and now it works as expected.
I'll try to figure out what caused it and follow up here. Just in case someone else comes across this.
Will close this in a few days if i can't find an explanation.
For now the problem is cleared up. Thank you for taking the time to help me figure this out so far.

**Comment by dam9000** [comment]
Great.
Perhaps it depends on terminal Theme variant:
![image](https://github.com/dam9000/kickstart-modular.nvim/assets/148590335/ed29e050-dece-4491-a447-5bd333cae0e3)

**Comment by marnux** [comment]
That is it indeed. Checked the terminal settings and that was on default/light. Switching it to dark, also made the background setting for nvim go to dark. I now get the colorscheme as expected.
