### ISSUE TITLE
Why couldn't show the buffer on the head of my neovim-kickstart-modular?

### ISSUE THREAD

**Issue by stingtam** [dam9000/kickstart-modular.nvim#20]
## Describe the bug

When I clone this repo, I got wonderful experience. But, I can't find the buffers. Please tell me how can I do? Thanks a lot.
## To Reproduce

1. ...

## Desktop

- OS: windows11 23H2
- Terminal: windows terminal

## Neovim Version 0.9.5
![neovim-issue](https://github.com/dam9000/kickstart-modular.nvim/assets/85009451/3408d6ce-9923-4863-87a6-c8bf8daa81ef)

```
```

**Comment by dam9000** [comment]
Type `<space><space>` to get a searchable list of buffers.
