### ISSUE TITLE
How to override default configuration for formatters and linters?

### ISSUE THREAD

**Issue by KikeSenpai** [dam9000/kickstart-modular.nvim#22]
## Describe the bug

First it's not a bug, but more like a question:
`conform` and `nvim-lint` help don't say anything about overriding the default configuration or rules of any formatter or linter.
How can this be achieved? Do these plugins pickup config files inside a project? is there a way to add global configuration that these plugins will pick?
Perhaps it could be worth adding a NOTE with an exaple on how to do it for any language formatter/linter.

## To Reproduce

Format or lint any filetype for which you have a formatter or linter set.

## Desktop

- OS: macOS Sonoma 14.4.1
- Terminal: iTerm2

## Neovim Version

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1710088188
   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"
```

**Comment by dam9000** [comment]
I wouldn't know. It would be best if this question is raised in the respective plugins, they will be better able to answer this. The only examples that I use is the default kickstart provided `stylua` with `.stylua.toml` config file and the lsp `clang` with the `.clang-format` config file.
