### ISSUE TITLE
Workflow of keeping this modular repo up to date with the upstream repo

### ISSUE THREAD

**Issue by ErikLahm** [dam9000/kickstart-modular.nvim#34]
I am aware this issue will not fit the typical bug report structure and is in itself not a bug, but asking the question publicly and having it answered here might help people with similar questions.

The core question is: This repo is a fork of the original [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim) repo but makes significant changes to the repo structure due to the modular approach; how do you keep this repo updated with the changes from the upstream repo?

Before finding your repo, I tried to modularise my fork of the kickstart repo myself. Still, I quickly encountered the problem of incorporating upstream changes into my repo since most changes are inside the top-level `init.lua` file, which I tried to split up into submodules/ files.
The workaround I found was fetching the upstream changes and then updating them manually into the respective files. I am wondering if there is a better way to do this.

Thank you for considering answering this question here, but no hard feelings if this is not the right place, and you will close the issue immediately.

**Comment by dam9000** [comment]
Initially I made the split manually but after a couple of merges I encountered the same issue as you have and keeping this updated manually is too much work so I made a set of scripts that split the init.lua to separate modules. The scripts themselves are really not pretty and they need to be updated occasionally when the parsing breaks, so I'm not too keen in releasing them at least not in the current form.

**Comment by ErikLahm** [comment]
Thanks a lot.
The insight you are using scripts for is already helpful, as now I know there is no other obvious solution I was unaware of.
If one day you feel like sharing the scripts, I would be more than grateful, but I understand that, for now, you would like to keep them in the drawer.
