### ISSUE TITLE
why the split of plugins

### ISSUE THREAD

**Issue by hoefkensj** [dam9000/kickstart-modular.nvim#46]
## Describe the bug

what is the point of separating your preselected plugins from the ones the user wiches to add, now there are 2 folders with plugins, wich makes making the config your own pretty hard since youre stuck with the separation unless you redo the thing 
why not just put them all in a single plugins folder , that way its clear how to add new ones as everything can be copied verbatum in the config but for the name  and its also clear where the plugins go , leaving no doubt if one were to come a cross a not working setup if it might work if its put in your folder instead of the custom one

## To Reproduce

1. ...

## Desktop

- OS: 
- Terminal: 

## Neovim Version

```
```

**Comment by dam9000** [comment]
You mean the "custom/plugins" path? It's done that way in order to prevent conflicts in case the upstream project adds/modifies plugins. But you can use any organisation you like, it's just a suggestion.
